-- Seven-day production log retention for CubedBot.
-- Run once in each Supabase project before starting a bot with database logging.

create table if not exists public.bot_logs (
    id bigint generated by default as identity primary key,
    entry_id uuid not null default gen_random_uuid(),
    created_at timestamptz not null default now(),
    level text not null check (level in ('DEBUG', 'INFO', 'WARN', 'ERROR')),
    stream text not null check (stream in ('stdout', 'stderr')),
    message text not null check (char_length(message) <= 8000)
);

create index if not exists bot_logs_created_at_idx
    on public.bot_logs (created_at desc);

create unique index if not exists bot_logs_entry_id_idx
    on public.bot_logs (entry_id);

alter table public.bot_logs enable row level security;

revoke all on table public.bot_logs from public, anon, authenticated, service_role;
grant insert, select on table public.bot_logs to service_role;
revoke all on sequence public.bot_logs_id_seq
    from public, anon, authenticated, service_role;
grant usage, select on sequence public.bot_logs_id_seq
    to service_role;

drop policy if exists "CubedBot may insert logs" on public.bot_logs;

create or replace function public.prune_bot_logs()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
    deleted_count integer;
begin
    delete from public.bot_logs
    where created_at < now() - interval '7 days';
    get diagnostics deleted_count = row_count;
    return deleted_count;
end;
$$;

revoke all on function public.prune_bot_logs() from public;
grant execute on function public.prune_bot_logs()
    to service_role;
